version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public/downloads:/rails/public/downloads
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
